title: "Gabriele Cembalo"
description: "Hi, I'm Gabriele Cembalo, I'm a Theoretical Physics student and this is my personal page. Here you can find some of my notes, ideas and software projects."
logo: /assets/img/Dirac2.png
theme: jekyll-theme-minimal
markdown: kramdown
