name: Generate Repo Architecture

on:
  push:
    branches:
      - main # cambia in master se il tuo branch principale si chiama master

jobs:
  visualize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Match Architecture
        uses: github/repo-visualizer@v1.1.1
        with:
          output_file: "repo-structure.svg" # Salviamo nella root per semplicità
          excluded_paths: ".github,README.md"

      - name: Commit and Push SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add repo-structure.svg
          git commit -m "Update repo structure diagram [skip ci]" || exit 0
          git push